import m from "mithril"
export const AppModal = {
  view(v) {
    return m(".modal.modal-slide-left.fade[id='siteSearchModal'][tabindex='-1'][role='dialog'][aria-labelledby='siteSearchModal'][aria-hidden='true']",
      m(".modal-dialog.modal-dialog-centered[role='document']",
        m("div.modal-content",
          m(".modal-body.p-all-0[id='site-search']",
            [
              m("button.close.light[type='button'][data-dismiss='modal'][aria-label='Close']",
                m("span[aria-hidden='true']",
                  m.trust("&times;")
                )
              ),
              m("div.form-dark.bg-dark.text-white.p-t-60.p-b-20.bg-dots",
                [
                  m("h3.text-uppercase.text-center.fw-300.",
                    " Search"
                  ),
                  m("div.container-fluid",
                    m("div.col-md-10.p-t-10.m-auto",
                      m("input..search.form-control.form-control-lg[type='search'][placeholder='Search Something']")
                    )
                  )
                ]
              ),
              m("div",
                [
                  m("div.bg-dark.text-muted.container-fluid.p-b-10.text-center.text-overline",
                    " results "
                  ),
                  m("div.list-group.list.",
                    [
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("img.avatar-img.rounded-circle[src='assets/img/users/user-3.jpg'][alt='user-image']")
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "Eric Chen"
                              ),
                              m("div.text-muted",
                                "Developer"
                              )
                            ]
                          )
                        ]
                      ),
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("img.avatar-img.rounded-circle[src='assets/img/users/user-4.jpg'][alt='user-image']")
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "Sean Valdez"
                              ),
                              m("div.text-muted",
                                "Marketing"
                              )
                            ]
                          )
                        ]
                      ),
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("img.avatar-img.rounded-circle[src='assets/img/users/user-8.jpg'][alt='user-image']")
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "Marie Arnold"
                              ),
                              m("div.text-muted",
                                "Developer"
                              )
                            ]
                          )
                        ]
                      ),
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("div.avatar-title.bg-dark.rounded",
                                m("i.mdi.mdi-24px.mdi-file-pdf")
                              )
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "SRS Document"
                              ),
                              m("div.text-muted",
                                "25.5 Mb"
                              )
                            ]
                          )
                        ]
                      ),
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("div.avatar-title.bg-dark.rounded",
                                m("i.mdi.mdi-24px.mdi-file-document-box")
                              )
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "Design Guide.pdf"
                              ),
                              m("div.text-muted",
                                "9 Mb"
                              )
                            ]
                          )
                        ]
                      ),
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("div.avatar.avatar-sm.",
                                m("div.avatar-title.bg-primary.rounded",
                                  m("i.mdi.mdi-24px.mdi-code-braces")
                                )
                              )
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "response.json"
                              ),
                              m("div.text-muted",
                                "15 Kb"
                              )
                            ]
                          )
                        ]
                      ),
                      m("div.list-group-item.d-flex.align-items-center",
                        [
                          m("div.m-r-20",
                            m("div.avatar.avatar-sm.",
                              m("div.avatar.avatar-sm.",
                                m("div.avatar-title.bg-info.rounded",
                                  m("i.mdi.mdi-24px.mdi-file-excel")
                                )
                              )
                            )
                          ),
                          m("div",
                            [
                              m("div.name",
                                "June Accounts.xls"
                              ),
                              m("div.text-muted",
                                "6 Mb"
                              )
                            ]
                          )
                        ]
                      )
                    ]
                  )
                ]
              )
            ]
          )
        )
      )
    )
  }
}
